import 'react';
import 'react-dom';
import 'redux';
import 'react-redux';
import 'react-router';
// import 'immutable';
// import 'redux-immutablejs';
import 'redux-logger';
import 'redux-thunk';
import 'babel-polyfill';
import 'lib-flexible';
// import './api/HDR.js';